---
- hosts: mywebservers
  become: yes
  gather_facts: yes
  tasks:
  - name: install webserver on ubantu ansible node
    apt:
          name: apache2
          state: present
    when: ansible_os_family=="Debian"
  - name: i want to start webserver
    service:
          name: apache2
          state: started
    when: ansible_os_family=="Debian"
  - name: install webserver on redhat ansible node
    yum:
          name: httpd
          state: present
    when: ansible_os_family=="RedHat"
  - name: i want to start webserver
    service:
          name: httpd
          state: started
    when: ansible_os_family=="RedHat"