---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: i want to install apache2 webserver on ansible node
    apt:
          name: apache2
          state: present
    when: ansible_os_family== "Debian"
  - name: i want to start webserver
    service:
          name: apache2
          state: started
    when: ansible_os_family== "Debian"
  - name: i want to install apache2 webserver on ansible red node
    yum:
          name: apache2
          state: present
    when: ansible_os_family== "RedHat"

  - name: i want to start webserver red
    service:
          name: apache2
          state: started
    when: ansible_os_family== "RedHat"