---
- hosts: mywebservers
  become: yes
  gather_facts: yes
  tasks:
  - name: install webserver  on ubuntu ansible nodes
    apt:
      name: "{{mywebserverpackonubuntu}}"
      state: present
    when: ansible_os_family== "Debian"

  - name: start webserver on ubuntu ansible nodes
    service:
      name: "{{mywebserverpackonubuntu}}"
      state: started
    when: ansible_os_family== "Debian"